carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home, checkout_done_view

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    # url(r'^product-detail/(?P<pk>\d+)/$', ProductDetail.as_view()),

]

ecomm_home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, contact_page
from accounts.views import LoginView, RegisterView, guest_register_view
from carts.views import cart_detail_api_view
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^guest/register/$', guest_register_view, name='guest_register'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^accounts/', RedirectView.as_view(url='/account/')),
    url(r'^account/', include('accounts.urls', namespace='accounts')),




    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Hello, world!</title>
     {% include 'base/css.html' %}
     {% block base_head %}{% endblock base_head %}
  </head>
  <body>
    {% include 'navbar.html' with brandname='Ecommerce' %}
    <div class="container">
        {% block content %}

        {% endblock content %}
        {% include 'base/js.html' %}

        <script>

            $(document).ready(function(){
                     // Auto Search
              var searchForm = $(".search-form")
              var searchInput = searchForm.find("[name='q']") // input name='q'
              var typingTimer;
              var typingInterval = 500 // .5 seconds
              var searchBtn = searchForm.find("[type='submit']")
              searchInput.keyup(function(event){
                // key released
                clearTimeout(typingTimer)

                typingTimer = setTimeout(perfomSearch, typingInterval)
              })

              searchInput.keydown(function(event){
                // key pressed
                clearTimeout(typingTimer)
              })

              function displaySearching(){
                searchBtn.addClass("disabled")
                searchBtn.html("<i class='fa fa-spin fa-spinner'></i> Searching...")
              }

              function perfomSearch(){
                displaySearching()
                var query = searchInput.val()
                setTimeout(function(){
                  window.location.href='/search/?q=' + query
                }, 1000)

              }









            var productForm = $(".form-product-ajax") // #form-product-ajax

            productForm.submit(function(event){
                event.preventDefault();
                // console.log("Form is not sending")
                var thisForm = $(this)
                // var actionEndpoint = thisForm.attr("action"); // API Endpoint
                var actionEndpoint = thisForm.attr("data-endpoint")
                var httpMethod = thisForm.attr("method");
                var formData = thisForm.serialize();

                $.ajax({
                  url: actionEndpoint,
                  method: httpMethod,
                  data: formData,
                  success: function(data){
                    var submitSpan = thisForm.find(".submit-span")
                    if (data.added){
                      submitSpan.html("In cart <button type='submit' class='btn btn-link'>Remove?</button>")
                    } else {
                      submitSpan.html("<button type='submit'  class='btn btn-success'>Add to cart</button>")
                     }
                    var navbarCount = $(".navbar-cart-count")
                    navbarCount.text(data.cartItemCount)
                    var currentPath = window.location.href

                    if (currentPath.indexOf("cart") != -1) {
                      refreshCart()
                    }
                  },
                  error: function(errorData){
                    console.log("error")
                    console.log(errorData)
                  }
                })

            })

            function refreshCart(){
              console.log("in current cart")
              var cartTable = $(".cart-table")
              var cartBody = cartTable.find(".cart-body")
              //cartBody.html("<h1>Changed</h1>")
              var productRows = cartBody.find(".cart-product")
              var currentUrl = window.location.href

              var refreshCartUrl = '/api/cart/'
              var refreshCartMethod = "GET";
              var data = {};
              $.ajax({
                url: refreshCartUrl,
                method: refreshCartMethod,
                data: data,
                success: function(data){

                  var hiddenCartItemRemoveForm = $(".cart-item-remove-form")
                  if (data.products.length > 0){
                      productRows.html(" ")
                      i = data.products.length
                      $.each(data.products, function(index, value){
                        console.log(value)
                        var newCartItemRemove = hiddenCartItemRemoveForm.clone()
                        newCartItemRemove.css("display", "block")
                        // newCartItemRemove.removeClass("hidden-class")
                        newCartItemRemove.find(".cart-item-product-id").val(value.id)
                          cartBody.prepend("<tr><th scope=\"row\">" + i + "</th><td><a href='" + value.url + "'>" + value.name + "</a>" + newCartItemRemove.html() + "</td><td>" + value.price + "</td></tr>")
                          i --
                      })

                      cartBody.find(".cart-subtotal").text(data.subtotal)
                      cartBody.find(".cart-total").text(data.total)
                  } else {
                    window.location.href = currentUrl
                  }

                },
                error: function(errorData){
                  console.log("error")
                  console.log(errorData)
                }
              })


            }



          })


        </script>









    </div>
  </body>
</html>

templates/home_page.html
{% extends 'base.html' %}

{% load static %}

{% block base_head %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock base_head %}


{% block content %}

    <div class="row">
        <div class="col-3">

        </div>
        <div class="col-6">
            <img src="{% static 'image/island.jpg' %}" style="height: 300px; width:400px">

            <h1>{{title}}</h1>
            <p>{{content}}</p>
        </div>
        <div class="col-3">

        </div>
    </div>

{% endblock content %}

templates/navbar.html
{% url 'home' as home_url %}
{% url 'login' as login_url %}
{% url 'contact' as contact_url %}
{% url 'register' as register_url %}
{% url 'products:list' as products_url %}
{% url 'cart:home' as cart_url %}
{% url 'accounts:home' as account_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">

        <a class="navbar-brand" href="http://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg">
            <img src="http://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
        </a>

      <a class="navbar-brand" href="{{ home_url }}">{% if brandname %}{{ brandname }}{% else %}Ecommerce site{% endif %}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if request.path == home_url %}active{% endif %}">
            <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% if request.path == products_url %}active{% endif %}">
            <a class="nav-link" href="{{ products_url }}">Products</a>
          </li>
          {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">Home</a>
                  <a class="dropdown-item" href="#">Billing</a>
                  <a class="dropdown-item" href="#">Preference</a>
                  <a class="dropdown-item" href="#">History</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
              </li>



          {% else %}
               <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a class="nav-link" href="{{ login_url }}">Login</a>
              </li>
              <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                <a class="nav-link" href="{{ register_url }}">Register</a>
              </li>
          {% endif %}
          <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
              <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items  }}</span> Cart</a>
          </li>
{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#              Dropdown#}
{#            </a>#}
{#            <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#              <a class="dropdown-item" href="#">Action</a>#}
{#              <a class="dropdown-item" href="#">Another action</a>#}
{#              <div class="dropdown-divider"></div>#}
{#              <a class="dropdown-item" href="#">Something else here</a>#}
{#            </div>#}
{#          </li>#}

        </ul>
       {% include 'search/snippets/search-form.html' %}
      </div>
  </div> <!-- container -->
</nav>